spring:
  application.name: spring
  datasource:
    url: jdbc:h2:mem:testdb # ????
    # url : jdbc:h2:file: ./data/testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
